### PR TITLE
Dependencies & Miscs

### PR DESCRIPTION
**Pull request by Tezirg**
- Dependencies update:
     - Updates `Grid2Op` dependency to 0.7.0
     - Updates sample `data` folder with scenario 000 and 037 generated with `grid2op==0.7.0`
     - Fix no longer existing dependency `dash-antd-components`
     - Moves dependency to `Grid2Kpi` as a submodule `kpi` of this package
- Miscs:
     - Fixed install process: `setup.py` dependencies, data and entry point function.  
     - Use absolute imports, as it is the pythonic way of doing. (https://docs.python.org/3/tutorial/modules.html#intra-package-references)
     - Removes unwanted sub-process, now starts with `app.run_server()` as intended by the dash framework
     - Improved config file and command line interface

 - Notes:
     - Tested with the package installed in edit mode and user mode.
     - Tested with the data under `data/agents` and data under `/tmp/data`

### CODE REVIEW

**Comment by MaximeMohandi** [comment]
Hello, 
I tested this modifications in a new virtual environment generated following the instruction given in readme.md
and it seems that there's no actions in any of the two agents. It cause the following problems :

__Overview page__
 - In inspector line, data aren't displayed.

__Macro page__
- In indicator line, data aren't displayed in both Types Action Repartition and Action Maintenance Duration.
- In Instant and Cumulated Reward the yellow dots representing actions aren't displayed.
- No action displayed in Distribution of Substation action and Distribution of line action.

I wonder if it could come from the changes made into the data folder

**Comment by Tezirg** [comment]
> Hello,
> I tested this modifications in a new virtual environment generated following the instruction given in readme.md
> and it seems that there's no actions in any of the two agents. It cause the following problems :
> 
> **Overview page**
> 
>     * In inspector line, data aren't displayed.
> 
> 
> **Macro page**
> 
>     * In indicator line, data aren't displayed in both Types Action Repartition and Action Maintenance Duration.
> 
>     * In Instant and Cumulated Reward the yellow dots representing actions aren't displayed.
> 
>     * No action displayed in Distribution of Substation action and Distribution of line action.
> 
> 
> I wonder if it could come from the changes made into the data folder

Hello, thanks for reviewing this bit of work,
I used datasets without any maintenances or hazards, as I don't have access to such datasets.
The `DoNothing` agent doesn't take any actions, obviously. The rdqn agent is a recurent nn which mostly does nothing as well.
 I may be able to generate new data, but its quite compute intensive for a greedy agent.

**Comment by mjothy** [comment]
@Tezirg : We really need to have agents that have actions to :
- Show the users what they can expect when they plug in theirs
- Test out the non regression of the changes we make

Can you please see with @BDonnot to produce agents that have actions, hazards and maintenance ?

@MaximeMohandi will test again once you update the data set.

Thank you very much for your work !

**Comment by Tezirg** [comment]
- I have added a script to generate the data samples directly under `grid2viz/data/agents/greedy-baseline` and `grid2viz/data/agents/do-nothing-baseline`. (It has compatibility for grid2op 0.8.0 that will be available pretty soon). 
 - I removed the 'unusable' sample datasets
 - The `greedy-baseline` does take actions and they show up correctly.

**Comment by Tezirg** [comment]
Update grid2op@0.8.1, tested OK with default `generate_data` output

**Pull request merged**
